### ISSUE TITLE
statgl_url can't find table ENX1ACT

### ISSUE THREAD

**Issue by johan-ejstrud** [StatisticsGreenland/statgl#4]
The table [ENE1ACT/ENX1ACT](https://bank.stat.gl/pxweb/en/Greenland/Greenland__EN__EN20/ENX1ACT.px/) isen't found by `statgl_url()`:

```
> statgl::statgl_url("ENX1ACT")
Error in statgl::statgl_url("ENX1ACT") : 
  Table 'ENX1ACT' not found in pxweb API
```

I can still, however, fetch the table manually by getting the API URL from the website and use `statgl_fetch`:
```
> statgl::statgl_fetch("https://bank.stat.gl:443/api/v1/da/Greenland/EN/EN20/ENX1ACT.px")
                      type          energivare value
1    Faktisk energiforbrug    Alle energivarer  8827
2    Faktisk energiforbrug             Gasolie  5463
3    Faktisk energiforbrug         Motorbenzin   815
```

**Comment by emilmalta** [comment]
Added a simple fix to `statgl_url`.

A proper lookup would be better, but I'm not sure how to implement it with this API. Looking into it.
