### ISSUE TITLE
statgl_meta - additional parameter?

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/statgl#5]
I get metadata from a table, using

hi <- statgl_meta("beesta")

but to get the info for a variablen I need to cycle through the lists returned

and find 

gender <- hi[[2]]

I can wrap this in a function
get_meta_var <- function(matrix, variable){ ... }

but think it could be generally useful to be able to call statgl_meta with an extra parameter, like:

hi <- statgl_meta("beesta","gender")

**Comment by larpSTATGL** [comment]
fx

library(statgl)

get_meta_code_value <- function(m,v){
  tmp <- statgl_meta(m)
    for (i in 1:length(tmp))
  {if (unique(getElement(getElement(tmp,i),"code"))==v) {return(hi[[i]])}}}

sex <- get_meta_code_value("BEDSTA","gender")

**Comment by emilmalta** [comment]
I don't think it's intuitive, as the user could either want codes or values, depending on context.

I would recommend using `purrr::pluck` and `dplyr::pull`. 

```
library(dplyr)
library(purrr)

statgl_meta("BEXSTNUK") %>%
  pluck("variables") %>% 
  pull(values, code)
```
