### ISSUE TITLE
statgl_meta additional metadata?

### ISSUE THREAD

**Issue by larpSTATGL** [StatisticsGreenland/statgl#6]
Is it possible to get more metadata from statgl_meta, like footnotes? (NOTE, NOTEX, VALUENOTE, CELLNOTE)

**Comment by emilmalta** [comment]
Yes, you can ask for the px file directly. E.g:

```{r}
px_content <- httr::content(
  httr::POST(
    url  = statgl_url("BEXSTNUK"), 
    body = statgl:::build_query(list(time = px_all()), "px")),
  as = "text"
)

px_content
```

You would probably want to make a named list in R, like:
```{r}
response_lines <- strsplit(px_content, ";\r\n")[[1]]
data_structure <- list()

for (line in response_lines) {
  parts <- strsplit(line, "=")[[1]]
  key <- parts[1]
  value <- parts[2]

  value <- gsub("\"", "", value)

  data_structure[[key]] <- value
}

data_structure
```

Only works because I know the values in that table_id. I'll make sure it's implemented in `statgl_meta`.

**Comment by emilmalta** [comment]
Implemented with `statgl_meta(table_id, returnclass = "px_list")`
